# Use the official Node.js image as the base image for frontend
FROM node:20.0.0-alpine AS frontend

# Set the working directory for frontend
WORKDIR /app/frontend

# Copy frontend package files
COPY frontend/package*.json ./

# Install frontend dependencies
RUN npm install

# Copy frontend source code
COPY frontend ./

# Build frontend
RUN npm run build

# Use nginx image
FROM nginx

# Copy in the fully build frontend into nginx
COPY --from=frontend /app/frontend/build /bin/www

# Copy in config file into nginx
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Expose nginx port
EXPOSE 80

# Run nginx
CMD [ "nginx", "-g", "daemon off;" ]